#!/bin/bash

sed -i "s|IMAGE=.*|IMAGE=${DOCKER_REPO}|g" docker/build-image.sh

if [[ "$SOURCE_BRANCH" = "develop" ]]; then
    ./docker/build-image.sh -d
elif [[ "$SOURCE_BRANCH" =~ ^release/.*$ ]]; then
    ./docker/build-image.sh -c
fi