# This workflow will only build for Pull Requests which are opened, changed , merged 
name: Docker build
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Jammy (ROS2 Humble)
jobs:
  docker-build-jammy:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
      file: ./jammy/Dockerfile
  docker-build-focal:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
      file: ./focal/Dockerfile