# This workflow will only build for Pull Requests which are opened, changed , merged 
name: Docker build
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker:
    steps:
    - name: Build Jammy (ROS2 Humble)
      uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
      file: ./jammy/Dockerfile
    - name: Build Focal (ROS1 Noetic/ ROS2 Foxy)
      uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
      file: ./focal/Dockerfile